### ISSUE TITLE
NSURLConnection/CFURLConnection HTTP load failed error

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [hallas/agent#20]
I'm trying to call an API which has the https scheme. The request is a POST with only one parameter. It fails with the following error. 

**NSURLConnection/CFURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9813)**

From what I found out about this error, I assume its because of SSL? How can I resolve this error?

I also found these delegate methods could be used to solve this.
https://developer.apple.com/library/mac/documentation/Foundation/Reference/NSURLConnectionDelegate_Protocol/Reference/Reference.html

http://stackoverflow.com/a/23242253/1077789

**Comment by hallas** [comment]
Hi! Will most likely change to use NSURLSession for better compatibility. Thanks for your patience

**Comment by hallas** [comment]
Should be fixed with the latest. If not it might because your domain was using an invalid certificate?
