### ISSUE TITLE
Build failed due to 

### ISSUE THREAD

**Issue by iFoxxy** [hallas/agent#31]
let res = response as! NSHTTPURLResponse

**Comment by hallas** [comment]
What version of xcode and swift?

**Comment by iFoxxy** [comment]
XCode 6.2
Swift version 1.1 (swift-600.0.57.4)
It seems to be a swift version problem, because forced conversion has been introduced in Swift 1.2, as I know.

**Comment by hallas** [comment]
Forgive me but are you using the latest version?

**Comment by iFoxxy** [comment]
I have downloaded it like 7 hours ago :)

**Comment by hallas** [comment]
I don't really understand then, please allow me to run some testing my self? Thanks for your patience mate.

**Comment by hallas** [comment]
@iFoxxy Did you have figure this out? I can't reproduce
