### ISSUE TITLE
Will it be fixed for Swift2 in Xcode7.0.1 

### ISSUE THREAD

**Issue by petershaw** [hallas/agent#32]
Hi, 

is there a fix for Xcode 7 in the pipeline? 
- The extra error in call is simple. 
- How to fix the "Cannot convert value of type (NSURLResponse..." Issue?

Thanks a lot, 
ps

**Comment by hallas** [comment]
Hi @petershaw 

Code is coming up : )

**Comment by lfarah** [comment]
@hallas when is it coming up?

**Comment by hallas** [comment]
@lfarah Hi. I'm sorry I don't have much time to work on this project. Maybe someone new can take over?

**Comment by lfarah** [comment]
@hallas I'd be happy to take over!

**Comment by iOSCowboy** [comment]
Hey @hallas. I've fixed the most urgent errors preventing the project from being compiled in Swift 2.0.

PR: #33

**Comment by hallas** [comment]
@lfarah Okay, that sounds good. How do you want to proceed then? We could create an organization and try to add more contributors.

**Comment by lfarah** [comment]
Yeah, let's do it!

**Comment by iOSCowboy** [comment]
Any chance to review the PR I submitted? :)

**Comment by hallas** [comment]
@iOSCowboy Yes for sure, as soon as we add more contributors it should be one of the firsts things we do.

**Comment by hallas** [comment]
Does anyone have an idea for an organisation name?

**Comment by zemirco** [comment]
I'd also like to help.

Why do you need an organization? Why not keep it under your username?

**Comment by lfarah** [comment]
@zemirco he wants to have more help and more people managing the lib

**Comment by zemirco** [comment]
There is not much missing. We simply have to make it work with Swift 3. 

Don't think we need an organization just for a single repo.

**Comment by rud0lph09** [comment]
We could go further than this.
